### ISSUE TITLE
Land-sea mask inconsistent with CMIP6 in LUC files

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/concordia#56] opened 2024-05-31 07:03 UTC
Originally opened by @dariak-bsc in #31 

> I ran the checker with the mask taken not from the reference file but from the corresponding variable in the file which is being checked, e.g. if I am checking the variable c3ann in the file multiple-states_input4MIPs_landState_RESCUE_PIK-MAgPIE-4-7-C-SSP2EU-NPi-2024.4.25_gn_2015-2100.nc then I am taking the missing values in c3ann at the first timestep as the mask to check the following timesteps. And in this case, I am not getting any missing values at the following timesteps. When I take the mask from the reference file, then I get missing values.

Is it fair to say (@dariak-bsc / @etiennesky / @pascal-sauer) that the issue here is what grid cells are considered land vs. ocean? 

Here is the map showing the delta between the reference data and the forcings land use mask:
![image](https://github.com/IAMconsortium/concordia/assets/1392657/7cf2ca9b-0481-46b5-b2d7-25314019173e)

**Comment by gidden** [comment] 2024-05-31 07:03
@dariak-bsc just for clarity, can you tell us what files precisely are being compared in the above image?

**Comment by etiennesky** [comment] 2024-05-31 08:41
yes it seems like the issue is at the border of oceans and inner lakes, so perhaps it's the remapping method that needs minor tweaking (e.g. using nearest neighbor or a binary land-sea mask)

**Comment by pascal-sauer** [comment] 2024-05-31 10:31
I'm working on a nearest neighbor approach

**Comment by dariak-bsc** [comment] 2024-06-03 15:15
> @dariak-bsc just for clarity, can you tell us what files precisely are being compared in the above image?

Hi @gidden , for this image, I took the files on the ftp:

- (1) esarchive_ftp/rescue/forcings/land_use/2024-04-25/multiple-states_input4MIPs_landState_RESCUE_PIK-MAgPIE-4-7-C-RESCUE-dir-v4p0-EocBudg1150-OAE-off-2024.4.25_gn_2015-2100.nc
- (2) esarchive_ftp/rescue/reference/landuse/multiple-states_input4MIPs_landState_CMIP_UofMD-landState-2-1-h_gn_2015.nc
 
I extracted the masks as the mask for `c3ann` at the first timestep for both files, and then calculated the difference between the mask for the file (1) and the mask for the file (2).

I did the same for the historical file provided by @etiennesky but it was equal to the mask for the file (2).

**Comment by coroa** [comment] 2024-09-10 08:33
@pascal-sauer I guess the newest version fixed the reported issue?

**Comment by pascal-sauer** [comment] 2024-09-16 08:04
yes, it is fixed now

**Closed by pascal-sauer** 2024-09-16 08:04 UTC
Labels: land-use, review/round-3
